nodeLinker: node-modules

logFilters:
  - level: discard
    pattern: "react is listed by your project with version * (*), which doesn't satisfy what @fluentui/react-icons and other dependencies request*"
